name: Publish slack message
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  workflow_run:
    workflows: [Build and push final image]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish-slack:
    runs-on: self-hosted
    steps:
      - run: echo 'The triggering workflow failed'
      - name: Publish slack message
        uses: ./.github/action_templates/slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job-status: ${{ job.status }}
          pull_request_url: ${{ github.event.pull_request.html_url }}
          head_commit_url: ${{ github.event.head_commit.url }}

