name: Build and push t-route image
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  workflow_run:
    workflows: [Build and push deps image]
    types:
      - completed
  workflow_dispatch:
    
jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          github-sha: ${{ github.sha }}
          image-name: "t-route"
          dockerfile-name: "Dockerfile.t-route"
  on-failure:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'